config/routes.rb
Kmedia::Application.routes.draw do

  resources :morning_lesson, only: [:show]

  scope '/(:locale)', constraints: { locale: /#{Language::UI_LANGUAGES.join('|')}/ } do

    resources :searches
    resources :feeds, only: [:index] do
      collection do
        get 'wsxml'
        get 'rss_video', format: :rss
        get 'morning_lesson', format: :rss
        get 'podcast', format: :rss
        get 'podcast1', format: :rss
        get 'rus_for_laitman_ru', format: :rss
        get 'rus_zohar', format: :rss
        get 'google_mapindex'
      end
    end

    resources :books, only: [:index, :show]

    resources :ui, only: [:index, :show] do
      collection do
        get 'homepage'
        get 'google_ads'
        get 'lesson_downloader'
      end
      member do
        get 'homepage_show'
        get 'next_lesson'
        get 'prev_lesson'
      end
    end

    resources :simple, only: [:index, :show]

    resources :typing, only: [:index] do
    end

    resources :comments, only: :create

    root to: 'ui#homepage'

    mount Ckeditor::Engine => '/ckeditor'

    devise_for :users
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
    end
    resources :users

    namespace(:admin) do
      root to: 'searches#index'

      resources :virtual_lessons do
        collection do
          get 'combine'
        end
        member do
          put 'reorder'
        end
      end
      resources :file_types
      resources :comments, only: [:index, :destroy]

      resources :censorship, only: [:index, :show] do
        member do
          post 'clear'
          post 'disable'
        end
      end

      resources :containers do
        member do
          get 'edit_long_descr'
          get 'edit_transcript'
          get 'mark_for_merge'
          put 'update_long_descr'
          put 'update_transcript'
          get 'merge_get_list'
          post 'merge'
          post 'send_to_censor'
        end
        collection do
          get 'get_update'
          post 'add_update'
          get 'combine'
        end
        resources :catalogs do
          member do
            get 'batch'
          end
        end
      end

      resources :selected_catalogs, only: [:index, :new, :edit, :update] do
        collection do
          get 'new_books'
          post 'set_books'
          post 'set_selected'
          get 'autocomplete'
        end
        member do
          delete 'unset_books'
          delete 'unset_selected'
        end
      end

      resources :file_assets
      resources :catalogs do
        collection do
          get :manage
          get :move_prepare
          get :move

          # required for Sortable GUI server side actions
          post :rebuild
        end
      end
      resources :departments
      resources :users do
        member do
          get :become
        end
      end
      resources :container_description_patterns
      resources :searches
      resources :dictionaries do
        collection do
          get :existing_suids
          get 'labels/existing_suids', to: 'labels#existing_suids'
          get 'labels/assignable', to: 'labels#assignable'
        end
        resources :labels
      end

      # using "post" method for the api calls because "get"  is being redirected to sign in page
      namespace :api do
        resources :tokens, only: [:create, :destroy]
        resources :api, only: [] do
          collection do
            post :register_file, :get_file_servers
            post :content_types, :file_types, :catalogs, :languages, :file_ids, :files, :patterns, :morning_lesson_files
            get :patterns
          end
          member do
          end
        end
      end
    end
  end

  # Redirect old landing pages
  get '/rss.php', to: 'feeds#rss_php', as: :rss_php, format: :rss
  get '/rss_video.php', to: 'feeds#rss_video', format: :rss

  get '/index.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/UILANG=RUS/)
      [301, { location: '/ru' }, []]
    when query.match(/UILANG=HEB/)
      [301, { location: '/he' }, []]
    when query.match(/SPA/)
      [301, { location: '/es' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/index_rus.html', to: proc { |env| [301, { location: '/ru' }, []] }
  get '/index_heb.html', to: proc { |env| [301, { location: '/he' }, []] }

  get '/smapless.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/CID=4500/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=4500' }, []]
    when query.match(/CID=1940/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=1940' }, []]
    when query.match(/CID=3691/)
      [301, { location: '/ru/ui?search%5Bcatalog_ids%5D=3691' }, []]
    when query.match(/CID=4613/)
      [301, { location: '/en/ui?search%5Bcatalog_ids%5D=4613' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/lesson-downloader.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    lang  = case
            when query.match(/UILANG=RUS/)
              'ru'
            when query.match(/UILANG=HEB/)
              'he'
            else
              'en'
            end
    [301, { location: "/#{lang}/ui/lesson_downloader" }, []]
  }

  get '*path', to: redirect('/'), status: 301, constraints: ->(request) { request.path !~ /rails\/routes/ }
end

app/controllers/admin/censorship_controller.rb
class Admin::CensorshipController < Admin::ApplicationController

  def index
    @containers = Container.for_censorship.page(params[:page])
  end

  def show
    @container    = Container.for_censorship.find(params[:id])
    @censor_email = @container.censor_id ? User.where(id: @container.censor_id).pluck(:email)[0] : nil
  end

  def clear
    container = Container.find(params[:id])
    container.update_attributes({
                                 for_censorship:   false,
                                 opened_by_censor: true,
                                 closed_by_censor: false,
                                 censor_id:        current_user.id
                             })
    @containers = Container.for_censorship.page(params[:page])
    render :index, notice: 'Opened'
  end

  def disable
    container = Container.find(params[:id])
    container.update_attributes({
                                 for_censorship:   false,
                                 opened_by_censor: false,
                                 closed_by_censor: true,
                                 censor_id:        current_user.id,
                                 catalogs:         [Catalog::CLOSED_BY_CENSORSHIP],
                                 virtual_lesson:   nil
                             })

    @containers = Container.for_censorship.page(params[:page])
    render :index, notice: 'Disabled forever'
  end
end

app/views/admin/censorship/index.html.haml
%header.subhead#overview
  %h2 Containers for Censorship
%section
  = paginate @containers

  %table.table.table-striped.table-bordered.table-condensed.lessons
    %thead
      %tr
        %th
        %th= sortable("id", "ID", @filter)
        %th= sortable("name", "Name", @filter)
        %th= sortable("filmdate", "Filmed", @filter)
        %th= sortable("created_at", "Created", @filter)
        %th= sortable("updated_at", "Updated", @filter)
        %th= sortable("lang", "Language", @filter)
        %th= sortable("secure", "Secure", @filter)
        %th{:colspan => 3} Actions
    %tbody
      -@containers.each do |container|
        %tr
          %td= check_box_tag "cb_#{container.id}", container.id, false, class: 'selected'
          %td{:class => container.marked_for_merge ? 'btn btn-warning' : ''}= container.id
          %td= container.name.truncate(57, :omission => '&hellip;').html_safe
          %td.created= container.filmdate.try(:to_date)
          %td= container.created_at.try(:to_date)
          %td= container.updated_at.try(:to_date)
          %td= container.lang
          %td= display_secure(container.secure)
          %td= link_to 'Show', admin_censorship_path(container)
          %td= link_to 'Clear', clear_admin_censorship_path(container), method: 'post'
          %td= link_to 'Disable Forever', disable_admin_censorship_path(container), method: 'post', :confirm => 'Are you sure?', :class => 'btn-small btn-danger nowrap'

app/views/admin/censorship/show.html.haml
%header.subhead#overview
  %h2 Censored Container

%section.well
  = display_show_item('ID', @container.id)
  = display_show_item('Name', @container.name)
  = display_show_item('Type', @container.content_type.try(:name))
  = display_show_item('Created', @container.created_at.to_s(:long_ordinal))
  = display_show_item('Updated', @container.updated_at.to_s(:long_ordinal))
  = display_show_item('Container date', @container.filmdate)
  = display_show_item('Language', @container.language)
  = display_show_item('Lecturer', @container.lecturer)
  = display_show_item('Secure', display_secure(@container.secure), true)
  = display_show_item('Labels', @container.labels.map{|lbl| lbl.display_name}.join(', '))
  = display_show_item('User', @container.user.try(:email))
  - if @container.opened_by_censor?
    = display_show_item('Opened by Censor', @censor_email)
%section
  %strong Descriptions:
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Language
        %th Container Description/Long Description
        %th Created at
        %th Updated at
        %th ID
    %tbody
      - @container.container_descriptions.each do |admin_container_desc|
        - next if (admin_container_desc.container_desc || admin_container_desc.descr).blank?
        %tr
          %td= admin_container_desc.lang
          %td
            = admin_container_desc.container_desc
            - unless admin_container_desc.descr.blank?
              %hr.soften.no-margin
              = admin_container_desc.descr
          %td= admin_container_desc.created_at.try(:to_date)
          %td= admin_container_desc.updated_at.try(:to_date)
          %td= admin_container_desc.id
%section
  %strong Transcripts:
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th Language
        %th TOC
        %th Transcript
        %th Created at
        %th Updated at
        %th ID
    %tbody
      - @container.container_transcripts.each do |t|
        - next if (t.transcript).blank?
        %tr
          %td= t.lang
          %td= t.toc.html_safe
          %td
            %a.btn{"data-toggle" => "modal", :href => "#myModal#{t.id}"}
              see transcript
            .modal.hide{:id => "myModal#{t.id}"}
              .modal-header
                %button.close{"data-dismiss" => "modal", :type => "button"} ×
                %h3=t.toc.html_safe
              .modal-body
                %p=t.transcript.html_safe
              .modal-footer
                %a.btn.btn-primary{"data-dismiss" => "modal", :href => "#"} Close
          %td= t.created_at.try(:to_date)
          %td= t.updated_at.try(:to_date)
          %td= t.id


%section
  %strong Catalogs:
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th ID
        %th Name
    %tbody
      - @container.catalogs.each do |catalog|
        %tr
          %td= catalog.id
          %td= catalog.name
%section
  %strong Files:
  %table.table.table-striped.table-bordered.table-condensed
    %thead
      %tr
        %th ID
        %th Name
        %th Security
        %th File Size
        %th File Duration
        %th Recorded at
        %th Created on
        %th Updated on
        %th Language
    %tbody
      - @container.file_assets.each do |asset|
        %tr
          %td= asset.id
          %td= link_to asset.name, asset.url, :target => '_blank'
          %td= display_secure asset.secure
          %td= number_to_human_size asset.size
          %td= convert_seconds_to_human_readable asset.playtime_secs
          %td= asset.date.try(:to_date)
          %td= asset.created_at.try(:to_date)
          %td= asset.updated_at.try(:to_date)
          %td= asset.lang