config/routes.rb
Kmedia::Application.routes.draw do

  resources :morning_lesson, only: [:show]

  scope '/(:locale)', constraints: { locale: /#{Language::UI_LANGUAGES.join('|')}/ } do

    resources :searches
    resources :feeds, only: [:index] do
      collection do
        get 'wsxml'
        get 'rss_video', format: :rss
        get 'morning_lesson', format: :rss
        get 'podcast', format: :rss
        get 'podcast1', format: :rss
        get 'rus_for_laitman_ru', format: :rss
        get 'rus_zohar', format: :rss
        get 'google_mapindex'
      end
    end

    resources :books, only: [:index, :show]

    resources :ui, only: [:index, :show] do
      collection do
        get 'homepage'
        get 'google_ads'
        get 'lesson_downloader'
      end
      member do
        get 'homepage_show'
        get 'next_lesson'
        get 'prev_lesson'
      end
    end

    resources :simple, only: [:index, :show]

    resources :typing, only: [:index] do
    end

    resources :comments, only: :create

    root to: 'ui#homepage'

    mount Ckeditor::Engine => '/ckeditor'

    devise_for :users
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
    end
    resources :users

    namespace(:admin) do
      root to: 'searches#index'

      resources :virtual_lessons do
        collection do
          get 'combine'
        end
        member do
          put 'reorder'
        end
      end
      resources :file_types
      resources :comments, only: [:index, :destroy]

      resources :censorship, only: [:index, :show] do
        member do
          post 'clear'
          post 'disable'
        end
      end

      resources :containers do
        member do
          get 'edit_long_descr'
          get 'edit_transcript'
          get 'mark_for_merge'
          put 'update_long_descr'
          put 'update_transcript'
          get 'merge_get_list'
          post 'merge'
          post 'send_to_censor'
        end
        collection do
          get 'get_update'
          post 'add_update'
          get 'combine'
        end
        resources :catalogs do
          member do
            get 'batch'
          end
        end
      end

      resources :selected_catalogs, only: [:index, :new, :edit, :update] do
        collection do
          get 'new_books'
          post 'set_books'
          post 'set_selected'
          get 'autocomplete'
        end
        member do
          delete 'unset_books'
          delete 'unset_selected'
        end
      end

      resources :file_assets
      resources :catalogs do
        collection do
          get :manage
          get :move_prepare
          get :move

          # required for Sortable GUI server side actions
          post :rebuild
        end
      end
      resources :departments
      resources :users do
        member do
          get :become
        end
      end
      resources :container_description_patterns
      resources :searches
      resources :dictionaries do
        collection do
          get :existing_suids
          get 'labels/existing_suids', to: 'labels#existing_suids'
          get 'labels/assignable', to: 'labels#assignable'
        end
        resources :labels
      end

      # using "post" method for the api calls because "get"  is being redirected to sign in page
      namespace :api do
        resources :tokens, only: [:create, :destroy]
        resources :api, only: [] do
          collection do
            post :register_file, :get_file_servers
            post :content_types, :file_types, :catalogs, :languages, :file_ids, :files, :patterns, :morning_lesson_files
            get :patterns
          end
          member do
          end
        end
      end
    end
  end

  # Redirect old landing pages
  get '/rss.php', to: 'feeds#rss_php', as: :rss_php, format: :rss
  get '/rss_video.php', to: 'feeds#rss_video', format: :rss

  get '/index.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/UILANG=RUS/)
      [301, { location: '/ru' }, []]
    when query.match(/UILANG=HEB/)
      [301, { location: '/he' }, []]
    when query.match(/SPA/)
      [301, { location: '/es' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/index_rus.html', to: proc { |env| [301, { location: '/ru' }, []] }
  get '/index_heb.html', to: proc { |env| [301, { location: '/he' }, []] }

  get '/smapless.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/CID=4500/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=4500' }, []]
    when query.match(/CID=1940/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=1940' }, []]
    when query.match(/CID=3691/)
      [301, { location: '/ru/ui?search%5Bcatalog_ids%5D=3691' }, []]
    when query.match(/CID=4613/)
      [301, { location: '/en/ui?search%5Bcatalog_ids%5D=4613' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/lesson-downloader.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    lang  = case
            when query.match(/UILANG=RUS/)
              'ru'
            when query.match(/UILANG=HEB/)
              'he'
            else
              'en'
            end
    [301, { location: "/#{lang}/ui/lesson_downloader" }, []]
  }

  get '*path', to: redirect('/'), status: 301, constraints: ->(request) { request.path !~ /rails\/routes/ }
end

app/controllers/admin/selected_catalogs_controller.rb
class Admin::SelectedCatalogsController < Admin::ApplicationController
  authorize_resource class: Catalog

  def index
    @catalogs = Catalog.selected_catalogs_ar('ENG').includes(:parent)
    @books = Catalog.where(books_catalog: true).first
  end

  def new
    @catalog = Catalog.new
  end

  def edit
    @catalog = Catalog.find(params[:id])
  end

  def update
    @catalog = Catalog.find(params[:id])
    authorize! :update, @catalog

    if @catalog.update_attribute(:selected_catalog, params[:catalog][:selected_catalog])
      redirect_to admin_selected_catalogs_url, :notice => "Successfully updated catalog."
    else
      render :edit
    end
  end

  def new_books
    @catalog = Catalog.new
  end

  def set_books
    name = params[:catalog][:name]
    catalog = Catalog.where(name: name).first
    books_catalogs = Catalog.where(books_catalog: true)
    if catalog && books_catalogs.each{|catalog| catalog.update_attribute(:books_catalog, false)} && catalog.update_attribute(:books_catalog, true)
      redirect_to admin_selected_catalogs_url, :notice => "Successfully selected Books Root Catalog."
    else
      @catalog = Catalog.new({name: name})
      @catalog.errors.add(:name, "Catalog \"#{name}\" does not exist.")
      render :new_books
    end
  end

  def unset_books
    Catalog.find(params[:id]).update_attribute(:books_catalog, false)
    redirect_to :action => 'index', :notice => "Successfully unselected Books Root Catalog."
  end

  def set_selected
    name = params[:catalog][:name]
    catalog = Catalog.where(name: name).first
    if catalog && catalog.update_attribute(:selected_catalog, params[:catalog][:selected_catalog])
      redirect_to admin_selected_catalogs_url, :notice => "Successfully selected catalog."
    else
      @catalog = Catalog.new({name: name})
      @catalog.errors.add(:name, "Catalog \"#{name}\" does not exist.")
      render :new
    end
  end

  def unset_selected
    @catalog = Catalog.find(params[:id])
    if @catalog.update_attribute(:selected_catalog, 0)
      redirect_to :action => 'index', :notice => "Successfully unselected catalog."
    else
      render :index, notice: "Unable to unselect catalog #{@catalog.name}"
    end
  end

  def autocomplete
    catalogs = Catalog.order(:name).where('name like ?', "#{params[:term]}%").pluck(:name)
    render json: catalogs
  end
end

app/views/admin/selected_catalogs/_books_form.html.slim
= display_actions f, admin_selected_catalogs_url

hr.soften
= display_errors f
.row
  .span12
    = f.input :name, label: 'Name', input_html: {class: 'span5', data: {autocomplete_source: autocomplete_admin_selected_catalogs_path}}
hr.soften
= display_actions f, admin_selected_catalogs_url

app/views/admin/selected_catalogs/_form.html.haml
= display_actions f, admin_selected_catalogs_url

%hr.soften
= display_errors f
.row
  .span12
    = f.input :name, label: 'Name', input_html: {class: 'span5', disabled: fix_name, data: {autocomplete_source: autocomplete_admin_selected_catalogs_path}}
    = f.input :selected_catalog, label: 'Position', input_html: {class: 'span2'}
%hr.soften
= display_actions f, admin_selected_catalogs_url

app/views/admin/selected_catalogs/edit.html.haml
%header.subhead#overview
  %h2 Change Order of Selected Catalog

= simple_form_for @catalog, url: admin_selected_catalog_path, method: :put do |f|
  = render 'form', f: f, fix_name: true

app/views/admin/selected_catalogs/index.html.slim
header.subhead#overview
  h2 Special Catalogs
  p
    - if can?(:create, Catalog) && Catalog.count_selected_catalogs < 5
      = link_to "New Selected Catalog", new_admin_selected_catalog_path, :class => 'btn btn-success btn-large pull-left'
    = link_to "New Books Root Catalog", new_books_admin_selected_catalogs_path, :class => 'btn btn-success btn-large pull-right'
  h4.clear &nbsp;

section
  h2 Selected Catalogs
  table.table.table-striped.table-bordered.table-condensed
    thead
      tr
        th Position
        th Name
        th Label
        th Secure
        th Visible
        th Open
        th Action
    tbody
      - @catalogs.each do |catalog|
        tr(class="#{cycle('odd', 'even')}")
          td.small = catalog.selected_catalog
          td
            - if catalog.parent
              span.small
                = catalog.parent.name.gsub(/\//, ' / ')
                '  (
                = catalog.parent_id
                '  ) /
            span.bold
              = catalog.name.gsub(/\//, ' / ')
              span.small
                '  (
                = catalog.id
                |  )
          td.small = catalog.label
          td = display_secure(catalog.secure)
          td = catalog.visible ? 'visible' : 'hidden'
          td = catalog.open ? 'open' : 'closed'
          td
            -if can?(:update, catalog)
              = link_to 'Edit', edit_admin_selected_catalog_path(catalog)
          td
            - if can?(:destroy, catalog)
              = link_to 'Remove', unset_selected_admin_selected_catalog_path(catalog), :confirm => 'Are you sure?', :method => :delete, :class => 'btn-small btn-danger'

- if @books.present?
  section
    h2 Books Root Catalog
    table.table.table-striped.table-bordered.table-condensed
      thead
        tr
          th Name
          th Label
          th Secure
          th Visible
          th Open
          th Action
      tbody
        tr(class="#{cycle('odd', 'even')}")
          td
            - if @books.parent
              span.small
                = @books.parent.name.gsub(/\//, ' / ')
                '  (
                = @books.parent_id
                '  ) /
            span.bold
              = @books.name.gsub(/\//, ' / ')
              span.small
                '  (
                = @books.id
                |  )
          td.small = @books.label
          td = display_secure(@books.secure)
          td = @books.visible ? 'visible' : 'hidden'
          td = @books.open ? 'open' : 'closed'
          td
            -if can?(:destroy, @books)
              = link_to 'Remove', unset_books_admin_selected_catalog_path(@books), :confirm => 'Are you sure?', :method => :delete, :class => 'btn-small btn-danger'

app/views/admin/selected_catalogs/new.html.haml
%header.subhead#overview
  %h2 New Selected Catalog

= simple_form_for @catalog, url: set_selected_admin_selected_catalogs_path, method: :post do |f|
  = render 'form', :f => f, fix_name: false

app/views/admin/selected_catalogs/new_books.html.slim
header.subhead#overview
  h2 New Books Root Catalog

= simple_form_for @catalog, url: set_books_admin_selected_catalogs_path, method: :post do |f|
  = render 'books_form', :f => f