config/routes.rb
Kmedia::Application.routes.draw do

  resources :morning_lesson, only: [:show]

  scope '/(:locale)', constraints: { locale: /#{Language::UI_LANGUAGES.join('|')}/ } do

    resources :searches
    resources :feeds, only: [:index] do
      collection do
        get 'wsxml'
        get 'rss_video', format: :rss
        get 'morning_lesson', format: :rss
        get 'podcast', format: :rss
        get 'podcast1', format: :rss
        get 'rus_for_laitman_ru', format: :rss
        get 'rus_zohar', format: :rss
        get 'google_mapindex'
      end
    end

    resources :books, only: [:index, :show]

    resources :ui, only: [:index, :show] do
      collection do
        get 'homepage'
        get 'google_ads'
        get 'lesson_downloader'
      end
      member do
        get 'homepage_show'
        get 'next_lesson'
        get 'prev_lesson'
      end
    end

    resources :simple, only: [:index, :show]

    resources :typing, only: [:index] do
    end

    resources :comments, only: :create

    root to: 'ui#homepage'

    mount Ckeditor::Engine => '/ckeditor'

    devise_for :users
    devise_scope :user do
      get '/login' => 'devise/sessions#new'
    end
    resources :users

    namespace(:admin) do
      root to: 'searches#index'

      resources :virtual_lessons do
        collection do
          get 'combine'
        end
        member do
          put 'reorder'
        end
      end
      resources :file_types
      resources :comments, only: [:index, :destroy]

      resources :censorship, only: [:index, :show] do
        member do
          post 'clear'
          post 'disable'
        end
      end

      resources :containers do
        member do
          get 'edit_long_descr'
          get 'edit_transcript'
          get 'mark_for_merge'
          put 'update_long_descr'
          put 'update_transcript'
          get 'merge_get_list'
          post 'merge'
          post 'send_to_censor'
        end
        collection do
          get 'get_update'
          post 'add_update'
          get 'combine'
        end
        resources :catalogs do
          member do
            get 'batch'
          end
        end
      end

      resources :selected_catalogs, only: [:index, :new, :edit, :update] do
        collection do
          get 'new_books'
          post 'set_books'
          post 'set_selected'
          get 'autocomplete'
        end
        member do
          delete 'unset_books'
          delete 'unset_selected'
        end
      end

      resources :file_assets
      resources :catalogs do
        collection do
          get :manage
          get :move_prepare
          get :move

          # required for Sortable GUI server side actions
          post :rebuild
        end
      end
      resources :departments
      resources :users do
        member do
          get :become
        end
      end
      resources :container_description_patterns
      resources :searches
      resources :dictionaries do
        collection do
          get :existing_suids
          get 'labels/existing_suids', to: 'labels#existing_suids'
          get 'labels/assignable', to: 'labels#assignable'
        end
        resources :labels
      end

      # using "post" method for the api calls because "get"  is being redirected to sign in page
      namespace :api do
        resources :tokens, only: [:create, :destroy]
        resources :api, only: [] do
          collection do
            post :register_file, :get_file_servers
            post :content_types, :file_types, :catalogs, :languages, :file_ids, :files, :patterns, :morning_lesson_files
            get :patterns
          end
          member do
          end
        end
      end
    end
  end

  # Redirect old landing pages
  get '/rss.php', to: 'feeds#rss_php', as: :rss_php, format: :rss
  get '/rss_video.php', to: 'feeds#rss_video', format: :rss

  get '/index.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/UILANG=RUS/)
      [301, { location: '/ru' }, []]
    when query.match(/UILANG=HEB/)
      [301, { location: '/he' }, []]
    when query.match(/SPA/)
      [301, { location: '/es' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/index_rus.html', to: proc { |env| [301, { location: '/ru' }, []] }
  get '/index_heb.html', to: proc { |env| [301, { location: '/he' }, []] }

  get '/smapless.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    case
    when query.match(/CID=4500/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=4500' }, []]
    when query.match(/CID=1940/)
      [301, { location: '/he/ui?search%5Bcatalog_ids%5D=1940' }, []]
    when query.match(/CID=3691/)
      [301, { location: '/ru/ui?search%5Bcatalog_ids%5D=3691' }, []]
    when query.match(/CID=4613/)
      [301, { location: '/en/ui?search%5Bcatalog_ids%5D=4613' }, []]
    else
      [301, { location: '/en' }, []]
    end
  }

  get '/lesson-downloader.php', to: proc { |env|
    query = env['QUERY_STRING'].upcase
    lang  = case
            when query.match(/UILANG=RUS/)
              'ru'
            when query.match(/UILANG=HEB/)
              'he'
            else
              'en'
            end
    [301, { location: "/#{lang}/ui/lesson_downloader" }, []]
  }

  get '*path', to: redirect('/'), status: 301, constraints: ->(request) { request.path !~ /rails\/routes/ }
end

app/views/common_ui/_one_container.html.slim
h4
  = type_of_item(item, '')
  | &nbsp;/&nbsp;
  span = film_date(item)
  | &nbsp;/&nbsp;
  a href="#{ui_path(item)}"
    == container_title(item, container_description(item))
    - playtime = item.playtime_secs.to_i
    - if playtime > 0
      | &nbsp;
      span
        = Time.at(playtime).utc.strftime('(%H:%M:%S)')
- available_languages = FileAsset.available_languages(item.file_assets)
.languages-bar
  ul.nav.nav-tabs
    li.tabs-title = t('ui.last_lesson.available_languages')
    - available_languages.each_with_index do |l, idx|
      li
        a href="##{l}-#{item.id}" data-toggle='tab' = l.upcase
.tab-content
  - available_languages.each_with_index do |l, idx|
    .tab-pane.fade.in id="#{l}-#{item.id}"
      - item_file_assets = item.file_assets
      .pull-left
        - unless only_download
          h5 = t('ui.container.download')
        = download_containers(item_file_assets, 'video', l)
        = download_containers(item_file_assets, 'audio', l)
        = download_containers(item_file_assets, 'text', l, true)
        = download_containers(item_file_assets, 'graph', l, true)
      - unless only_download
        .pull-left.padding-left
          h5 = t('ui.lesson.view_play')
          = download_containers(item_file_assets, 'video', l, true)
          = download_containers(item_file_assets, 'audio', l, true)

app/views/common_ui/_sidebar.html.slim
#sidebar.span3 data-title='#{t('ui.sidebar.sidebar')}'
  .new-site
    a.btn.btn-block.btn-primary.btn-large href=t('ui.sidebar.new_site_url') == t('ui.sidebar.new_site_title')
  ul.nav.nav-list
    li.clear-filters
      button.btn.btn-block.btn-primary = t('ui.sidebar.clear_all_filters')
  - if @books_catalog
    .books-catalog-button
      = link_to @books_catalog['name'], books_path, class: 'btn btn-block btn-inverse'
  ul.nav.nav-list
    li.divider
    li.nav-header = t('ui.sidebar.filter_by_date')
    li
      javascript:
        dates_range_value = '#{ search.date_one_day rescue Date.today }';
      .dates_range
    li.divider
  ul.nav.nav-list
    li.nav-header = t('ui.sidebar.filter_by_content_type')
    == content_type('all', search.content_type)
    == content_type('lesson', search.content_type)
    == content_type('lecture', search.content_type)
    == content_type('program', search.content_type)
    == content_type('song', search.content_type)
    == content_type('clip', search.content_type)
    == content_type('book', search.content_type)
    == content_type('declamation', search.content_type)
    li.divider
  ul.nav.nav-list
    li.nav-header= t('ui.sidebar.filter_by_media_type')
    == media_type('all', search.media_type)
    == media_type('audio', search.media_type)
    == media_type('video', search.media_type)
    == media_type('text', search.media_type)
    == media_type('image', search.media_type)
    li.divider
  ul.nav.nav-list
    li.nav-header= t('ui.sidebar.filter_by_language')
    li
      - options = options_for_select([[t('ui.sidebar.language.all'), 'all']] + Language.order(:language).all.map{|l| ["#{l.language} (#{l.locale})", l.code3]}, selected: search.language)
      = select_tag :language_ids, options, include_blank: false